### ISSUE TITLE
FE : Multiple Socket Connections for Single User

### ISSUE THREAD

**Issue by Hakeemmidan** [hatchways/team-eagle#112]
- I think we're creating too many socket connections for a single user
- Below: I created a single user that doesn't have any friends (I emptied the DB too), but here is what server logged on refresh:
![mutliple-connections-for-single-user](https://user-images.githubusercontent.com/27740273/84452066-a28c2c80-ac09-11ea-98ac-949d3038cbc7.gif)

  - We ideally want to take this down to 1 socket connection for each user

**Comment by dotslash227** [comment]
I had noticed the issue and Fixed it in of the the new PR's.

**Comment by dotslash227** [comment]
Had fixed the crashing in "Change profile picture feature" PR.
