### ISSUE TITLE
FS: Friends page + Model

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-eagle#18]
Front-end:
- A front-end web page to add friends 
- Sketch goal (filter by name for following and suggested friends)

Backend:
- Friends model - a user follows many friends
- API routes:
    - get suggested friends (random) - search query (search by name)
    - get your following - search query by name
    - follow / unfollow friend (POST request)

Forward thinking:
- How can we create a friend's graph?

**Comment by Hakeemmidan** [comment]
To create a friends graph, I'm thinking about making the `UserSchema` have something like this:
```JavaScript
friend_ids: [
  {
    type: String,
    required: true,
  }
]
```

And then using the [$graphLookup MongoDB function](https://docs.mongodb.com/manual/reference/operator/aggregation/graphLookup/) to traverse through the graph. It would be [something like this](https://medium.com/dbkoda/optimising-graph-lookups-in-mongodb-49483afb55c8).

Why will we need to traverse deeper than 1 level for friends? Is it to find mutual connections at varying degrees?
