### ISSUE TITLE
BE: Login / Signup Routes

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-eagle#8]
**Register route (POST)**
- this will create a new user, return 201
- validation on the back-end - password should be atleast 6 characters, required fields (email, name), checking confirm and password are the same
- return a JWT token

**Login route (POST)**
- verify username and password
- return 4xx if things are incorrect
- return the JWT token
- User model, don't want to save password directly on the database (hash/salt before we save them)

- Take a look at https://docs.google.com/presentation/d/18O0Yojq976gnwWCkfXWEC8o4lBOg42DjuS4Xf3YzCvk/edit

**Comment by Hakeemmidan** [comment]
For the login route, we're going to use email and password as the required fields, right?

It shows email on the mocks but username in here so I wanted to double-check
